# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-b2open-treinamento"
BBFILE_PATTERN_meta-b2open-treinamento = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-b2open-treinamento = "11"

LAYERDEPENDS_meta-b2open-treinamento = "core"
LAYERSERIES_COMPAT_meta-b2open-treinamento = "dunfell kirkstone"

BBFILES_DYNAMIC += " \
    qt5-layer:${LAYERDIR}/dynamic-layers/qt5-layer/*/*/*.bb \
    qt5-layer:${LAYERDIR}/dynamic-layers/qt5-layer/*/*/*.bbappend \
"
