PACKAGECONFIG = "\
                 release \
                 tools \
                 accessibility \
                 dbus \
                 glib \
                 freetype \
                 harfbuzz \
                 jpeg \
                 libpng \ 
                 gif \
                 ico \
                 icu \
                 zlib \
                 pcre \
                 eglfs \
                 gles2 \
                 kms \
                 tslib \
                 sql-sqlite \
                 evdev \
                 fontconfig \
                 linuxfb \
                 widgets \
                 udev \
                 tools \
                 vulkan \
                 openssl \
                 "
